# %% Hyper Parameter
Rpeak = []
Speak = []
SpeakLoc = []
QpeakLoc = []
Rprevious = []
Rend = []
RPstart = []
RTend = []
Qpeak = []
QSamp = []

STACKS = []
PEAK_STACK = []
SIGNAL_STACK = []
LABEL_STACK = []
RR_INTERVAL = []
TIME_HRV_FEATURE = []
FREQUENCY_HRV_FEATURE = []
POINCARE_HRV_FEATURE = []
CSICVI_HRV_FEATURE = []